meta_product_name: "BisImpact"
meta_title: "Biswas Social Impact Advisory | Management Consulting | BisImpact"
meta_description: "World class experts at supporting corporate entities and philanthropists to make a social difference"
meta_image: "logo-blue.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
