meta_product_name: "Bisimpact"
meta_title: "Biswas Social Impact Advisory"
meta_description: "Experts at supporting corporate entities and philanthropists to make a social difference"
meta_image: "logo-real.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
